### ISSUE TITLE
OBS seem to have ability to change state locally in the controls

### ISSUE THREAD

**Issue by glennawatson** [maxrumsey/OzStrips#10]
I am a OBS and can seem to change values for the strips locally. In the code there doesn't seem to be much readonly protection based on having a OBS.

Might be useful to just set the "ReadOnly" property on the strip controls if the user has only OBS.

**Comment by suteeyt** [comment]
Noticed my strips being moved back and forth when was online. Might've been an OBS.

**Comment by maxrumsey** [comment]
@suteeyt , if you were on ML ADC that'd be me, i was just making sure strips would coordinate (go blue).

@glennawatson , if you're connected as an observer, you can move strips around locally, set holding point, add queue bars, but these wont sync to the server.

SocketConn.cs
```
        private bool CanSendDTO
        {
            get
            {
                if (!(Network.Me.IsRealATC || isDebug)) AddMessage("c: DTO Rejected!");
                return io.Connected && (Network.Me.IsRealATC || isDebug);
            }
        }
```

if you're debugging with visual studio, there is an override in there for that, to ease development, which may have caused what you saw

nothing you change should update in the vatsys strips (ie altitude, runway, sid), (excluding squawks), due to checks on the vatsys side.
